### ISSUE TITLE
[Proposal] Create a Group from Galxe Passport Token holders

### ISSUE THREAD

**Issue by ZKentin** [sismo-core/sismo-hub#1450]
A Galxe Passport Token is a non-transferable ERC-721 NFT that is the on-chain representation of an off-chain KYC verified identity.

Creating the Galxe Passport Token Group will enable to generate new sybil-resistant Groups from members that are unique humans verified by a KYC.

### Specifications

Expected Group: list of all addresses holding a Galxe Passport Token. 

### Tips on how to create the Group

Galxe Passport Token is minted on BNB Chain with [this](https://bscscan.com/token/0xe84050261cb0a35982ea0f6f3d9dff4b8ed3c012) contract address.

The easiest way to extract the list of addresses is by using BigQuery.

Have a look at [Sismo documentation](https://docs.sismo.io/sismo-docs/tutorials/create-your-zk-badge-in-15-minutes-developers) to understand how to generate a group.

Have fun!

**Comment by sampolgar** [comment]
The Sismo BigQuery supports Polygon & Mainnet. We have have an Ankr data provider which I used in this group generator.
I couldn't test this with the free API key as it requires premium due to the number of requests required. 
I'd love to test before making a PR!

Here's [my branch](https://github.com/sismo-core/sismo-hub/compare/main...sampolgar:sismo-hub:group-galxepassport)

**Comment by MartinGbz** [comment]
The PR https://github.com/sismo-core/sismo-hub/pull/1709 has been merged

**Comment by MartinGbz** [comment]
Thanks a lot @sampolgar for your new contribution to the Sismo Hub! 💜
